[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "common",
    "protocols",
    "plugins",
    "tests",
]

[workspace.package]
version = "0.3.4"
license = "MPL-2.0"
edition = "2024"
repository = "https://github.com/hollowpointer/zond"

[workspace.dependencies]
anyhow = "1.0.99"
async-trait = "0.1.86"
colored = "3.1.1"
clap = { version = "4.5.45", features = ["derive"] }
pnet = "0.35.0"
rand = "0.9.2"
indicatif = "0.18.0"
console = "0.16.1"
thiserror = "2.0.11"
crossterm = "0.29.0"
rayon = "1.11.0"
tracing = "0.1.44"

zond-core = { path = "./core" }
zond-common = { path = "./common" }
zond-protocols = { path = "./protocols" }
zond-plugins = { path = "./plugins" }
